language: python
python:
  - "3.5"
#  - "3.6"  # Commented out until pylint support gets implemented, https://github.com/PyCQA/pylint/issues/1072
install:
  - "pip install tox-travis"
script:
  - "tox"  # Will run with the travis-defined python environment
  - "tox -e coverage"
after_script:
  - "pip install codacy-coverage"
  - "python-codacy-coverage -r coverage.xml"
